### ISSUE TITLE
split io-streams-core into separate package

### ISSUE THREAD

**Issue by winterland1989** [snapframework/io-streams#58]
I am asking for a release of a separate package which only contain core types, combinators and ByteString modules, our use case is a raw tcp server, and we have our own network adapter because the standard one is some what limited, I ask for such one split for the sake of reducing compilation time. Do you considered this proposal is ok? I'm volunteered to make such a change : )

**Comment by hvr** [comment]
I just tried locally, `time cabal install -j --dep` in an empty sandbox takes up

```
real	1m53.268s
user	2m50.428s
sys	0m3.060s
```

wherease the final `time cabal install -j` took just

```
$ time cabal install -j 
Resolving dependencies...
Notice: installing into a sandbox located at
/tmp/io-streams-1.3.5.0/.cabal-sandbox
Configuring io-streams-1.3.5.0...
Building io-streams-1.3.5.0...
Installed io-streams-1.3.5.0

real	0m10.204s
user	0m9.032s
sys	0m0.504s
```

Which part of the compilation time is bothering you specifically?

**Comment by winterland1989** [comment]
IMHO, 2 min is quite long for a fresh compilation 😄 . In my use case, i really don't want to pull in attoparsec, zlib or process.

**Comment by mightybyte** [comment]
The `process` package ships out of the box with GHC.  So that has zero impact.  The zlib package takes 9 seconds to install from a fresh sandbox on my machine.  So IMO those two are not significant enough to warrant the split.  The bulk of the attoparsec time is taken up by text, vector, and hashable, which are core libraries that are very likely to already be included in most significant Haskell projects.  In fact, attoparsec itself is a pretty core package as well, with 552 reverse dependencies.

Another factor to consider here is that cabal has an upcoming feature currently called "new-build" (http://blog.ezyang.com/2016/05/announcing-cabal-new-build-nix-style-local-builds/) that will substantially reduce the amount of time spent building dependencies like this because it will cache previous builds.  You can use the tech preview of this functionality today by running `cabal new-build`.  See that above link for more information.

These are just factors to consider though.  I'll defer judgment on this issue to @gregorycollins since he is the primary maintainer of this package.

**Comment by winterland1989** [comment]
I understand your point, and current module's structure is quite nice BTW. My intuition is that even without the compilation time consideration. it's still a good thing to do the split: It doesn't affect compatibility, and it's a net gain for adapter authors. Let's wait on more voice on this proposal.

**Comment by gregorycollins** [comment]
Thanks for the request. I thought about it, but the downsides of splitting the library outweigh the benefits for me. It's batteries included, but there aren't that many of them: we tried to keep the dependency set of this library small and (for the most part) sticking to Haskell Platform packages.
