### ISSUE TITLE
Generalize to MonadUnliftIO?

### ISSUE THREAD

**Issue by BardurArantsson** [snapframework/io-streams#63]
I wonder if the maintainers would be open to generalizing to MonadUnliftIO?

The main thing that MonadUnliftIO brings is the ability to generalize IO to any ReaderT-like monad transformer. It also provides an instance of MonadIO, so that would mean that `io-streams` is "automatically" generalized to MonadIO. This (indirectly) allows for `bracket` over any `io-streams` operation.

This would incur a dependency on `unlift-core` and (transitively) `transformers`.

Just as an implementation note: The changes are mostly trivial, but would be pretty pervasive. I'm using `io-streams` in a project where I'm also using MonadUnliftIO and is usually pretty trivial to adapt everything, mostly just sprinkling around little bit of liftIO, wrapping with withRunInIO, etc. Of course that could also be an argument against adopting MonadUnliftIO -- but it's a bit of pain to have to do this adaptation in every project and AFAICT there's really nothing to lose by adopting MonadUnliftIO instead of IO. 

Any thoughts?

EDIT: I should add: If one is using this in a MonadIO or IO context absolutely nothing needs to change in client code, so AFAIK this would not actually impact any existing client code.

**Comment by hvr** [comment]
I strongly advise against using `MonadUnliftIO` and was rather hoping `io-streams` would if anything adopt the more principled [`execptions:Control.Monad.Catch`](http://hackage.haskell.org/package/exceptions-0.10.0/docs/Control-Monad-Catch.html) approach.

**Comment by BardurArantsson** [comment]
@hvr Do you have any arguments against MonadUnliftIO? Just saying that Catch, is "more principled" is rather vague.

Regardless, I can enumerate a few for preferring MonadUnliftIO for io-streams in particular:

* It's a *lot* simpler than MonadCatch, MonadMask, et. al. This is line with the io-streams philosophy of simplicity.
* It's a lot easier to write correct instances of MonadUnliftIO and *much* harder to write incorrect instances since it's just a single class method. It's usually impossible to get the types to even line up if you're trying to write a bad instance. Contrast this with the complexity of the laws (such as they are) for e.g. MonadCatch, MonadMask, etc.
* There are no dodgy instances out of the box, see e.g. the `Monad m => MonadMask (CatchT m)` instance documentation.
* There are no arbitrary choices wrt. "which state to keep/throw away" in cases of handlers throwing exceptions themselves since there's no instance for StateT at all.
* MonadUnliftIO generalizes the operation we actually *care* about -- MonadCatch, MonadMask etc. just gives each of the IO-equivalent functions its own class. (Unsatisfactorily, I find because of the complexity it leads to. It's an interesting experiment for sure to see if such laws could even be formulated.). However, programmers actually don't bare about any of the "mechanics" -- they just want a working `bracket` upon which everything else can be built.

Ultimately, I primarily care about *correctness* which means that simplicity is a good thing if we can achieve the same goals, and since io-streams always has IO at the "bottom" of the monad stack I don't see any reason to go with MonadCatch, MonadMask, etc. They are significantly more complex and with IO at the "bottom" we can achieve the same goal of generalization with MoandUnliftIO is a much simpler and robust way.

(Phew, that turned out longer than I intended...)

**Comment by BardurArantsson** [comment]
I should say: If the maintainers decide 'yes' on this, I'm volunteering to do the implementation myself.

(I've already considered doing a `unliftio-streams`, but considering the amount of Haddock, etc. it would be rather a chore to do this generalization as "facade" to io-streams.)

**Comment by mightybyte** [comment]
@gregorycollins can correct me if I'm wrong, but I believe the original point of io-streams was to build on the lowest level primitives...i.e. `IO`.  So I'm guessing `MonadUnliftIO` will be a no-go in the core io-streams package.  But Greg is the maintainer, so it's up to him.

**Comment by BardurArantsson** [comment]
I've done a small proof-of-concept here:  http://hackage.haskell.org/package/unliftio-streams

See e.g. https://github.com/BardurArantsson/unliftio-streams/blob/master/src/UnliftIO/Streams/Combinators.hs to see how small the changes really would be. It really is just sprinkling a with "runWithIO" and "liftIO" in there.

**Comment by mightybyte** [comment]
I'm not particularly thrilled about adopting a dependency on a concept self-described as "young, and will likely undergo some serious changes over time. It's also very lightly tested."  Also, I don't really see significant value in making this change.  The `io-streams` package is built on `IO`, a much more widely used and fundamental concept.  `MonadUnliftIO`ships out of the box with an instance for `IO`, so using `io-streams` with it should already be trivial.  It really doesn't seem worth the effort and extra dependency on a young and immature package.

**Comment by BardurArantsson** [comment]
Hm, where did you find that description text? It honestly sounds like it's just some obsolete text. (If you point me towards the text, I'll check with the maintainer(s) whether it should be changed.)

> MonadUnliftIOships out of the box with an instance for IO, so using io-streams with it should already be trivial. It really doesn't seem worth the effort and extra dependency on a young and immature package.

It's "trivial" in the sense that it's doable and should be doable to wrap the full API for io-streams in a UnliftIO-equivalent, but it does involve quite a bit of boilerplate lifting and unlifting where callbacks are involved; see the example I've already provided in my last comment.

Re: effort: I'm fully prepared to do the whole conversion as a PR -- it's not actually that bad. If it weren't for the problem of keeping up to date + having to copy (or losing) the documentation from io-streams, I'd actually just have "filled in" my unlifio-streams package already and called it a day. Further, having MonadUnliftIO in the code base would add basically zero additional maintenance effort. (Assuming I'm correct about the descriptive text about stability being correct -- again, I'll check with the maintainer(s).)

**Comment by BardurArantsson** [comment]
@emilypi I think you're missing the point of unliftio. The point isn't the existing instances, it's that it's trivial to write your own instances for any ReaderT-like monad. I'm not sure what your search is supposed to prove. I'm not saying that unliftio is relevant for io-streams *itself* -- only users of io-streams.

I also think you're also being a bit unfair by saying "lightly tested" and that it somehow breaks the philosophy of unliftio. It's actually incredibly simple.

 > So far, though, there is little to no documentation detailing the implications of this far-reaching and very very important changeset.  Many people have business value riding on Snap - breaking changes are untenable except in very special circumstances.

What kind of documentation are you looking for? This honestly just sounds like scare-mongering or a fear of change.

Regardless, I honestly don't care enough to fight an uphill battle on this. I guess I'll just settle for having to maintain unliftio-streams. *Sigh*

**Comment by emilypi** [comment]
There's no need to be combative about this - I respectfully disagreed and I stated why. Chil.

>The point isn't the existing instances, it's that it's trivial to write your own instances for any ReaderT-like monad. I'm not sure what your search is supposed to prove. I'm not saying that unliftio is relevant for io-streams itself -- only users of io-streams.

You are free to do this - as I stated in point 2 - in your own projects. But it does not jive with Snap's philosophy, nor it's current codebase (which is what the search was meant to show), so it would be a poor balance of convience vs. maintenance burden. 

>I also think you're also being a bit unfair by saying "lightly tested" and that it somehow breaks the philosophy of unliftio. It's actually incredibly simple.

I didn't say this - [snoyman did](https://i.imgur.com/2jXZbTG.png).

>What kind of documentation are you looking for? This honestly just sounds like scare-mongering or a fear of change.

This is a potential breaking change for folks using the current exception API. If that is not enough, then please reconsider your motivations for submitting the issue (note: I am not a Snap maintainer, or contributor). If it sounds like scare-mongering, please gain more experience with production software so that it strikes the correct fear within you. If you believe it is fear of change, please consider that `unliftio` is a very narrow use-case for a very narrow-minded style. I don't know what to tell you here.

>Regardless, I honestly don't care enough to fight an uphill battle on this. I guess I'll just settle for having to maintain unliftio-streams. Sigh

Such is the way of open source! If you disagree, you are always free to put in the hours to maintain your own software on your own time, affecting your own users. Remember, [uphill battles are good!](https://i.imgur.com/1aQ2Kpw.jpg)

**Comment by BardurArantsson** [comment]
> please gain more experience with production software so that it strikes the correct fear within you

Please don't patronize me (or anyone for that matter). I have quite a lot of experience with production software, thank you very much.

(I'm out, this has ceased being productive.)

**Comment by mightybyte** [comment]
Getting back to the topic of the issue, I don't think this is something that should go into `io-streams`.  As the above discussion indicates, there is clearly disagreement on the matter.  The three abstractions 
 at play here in order of most to least general are `IO`, `MonadIO`, and `MonadUnliftIO`.  `IO` is the most general because both of the other two depend on it.  `MonadUnliftIO` is the least general because it also depends on `MonadIO`.  `io-streams` is already built on the most general of these primitives, `IO`.  Both `MonadIO` and `MonadUnliftIO` provide instances for `IO`, so as I see it the current behavior is the most general and the one that we should stick with.

This library is about providing a general set of tools that give efficiency and generality to the maximum number of potential users, not providing maximum convenience for a particular preferred pattern of use.  To the extent that, as @BardurArantsson mentioned above, all you have to do is sprinkle some calls to `liftIO`, I would say that you don't even need a wrapper library.  Just call `liftIO` yourself and move on.  If the integration with `MonadUnliftIO` requires more work, then maybe a wrapper package would be appropriate.  But we should not do this with changes to the core library that impose extra dependencies on controversial packages on all our users.

**Comment by emilypi** [comment]
Apologies @BardurArantsson - that wasn't cool of me. You're right and I've edited out the offending comments from my post. Aside from the one comment, I've been informed that my tone was a little aggressive here, and that's not at all what I was going for.

**Comment by BardurArantsson** [comment]
@emilypi Personally, I wouldn't edit out bits of comments. That just seems disingenuous. (Not saying you are! I'm just saying that it makes it *seem* that way. Without a real audit trail, it's really easy to come to the wrong conclusion). This is why I think anyone responding to anything on an "editable" platform should always quote the thing they're responding to.

No hard feelings, btw, on the previous exchange :). This is obviously a controversial issue... I didn't think it was, but here we are.

@mightybyte Well, the "sprinkle liftIO + runWithIO" approach does get *really* tiresome once you have 1+ uses of anything io-streams. Still, I respect the decision and it's fair enough.

I'm really interested in the "breaking change" angle, just to see if I'm missing anything here. The only breaking (runtime) change I can see here would be altered exception behavior (as I think @emilypi pointed out), but are you perhaps thinking of breaking compilation? My overall philosophy is towards it being ok to break compilation as long as the answer is obvious, but I suppose that changes with the number of direct dependencies.

**Comment by hvr** [comment]
> I don't think it's actually possible to view previous versions of comments on GitHub

you think wrong ;-)

**Comment by mightybyte** [comment]
@BardurArantsson Yes, this is about breaking compilation.  Breaking compilation demands time and effort--in large codebases potentially very significant amounts of it--from users.  Regardless of whether the upgrade effort is straightforward or not, it is still effort.  Over the 8 years Snap has been around it has been used in core infrastructure being relied on in numerous mission-critical applications that I'm personally aware of and I'm sure many more that I'm not.  In highly important mission-critical applications every line of code changed is a risk, even if it's just a simple `liftIO`.  Even if your changes are straightforward, they're still risky for mission critical apps because of the unknown performance impact.  I'm personally aware of io-streams being used in applications that serve millions of requests per day with strict latency SLAs.  The tradeoff just doesn't make sense to me when the wrapper library you've already started solves all your problems with zero cost to the existing user base.

**Comment by BardurArantsson** [comment]
@hvr Ah, yes. Not sure how I've missed that for so long. I'm glad to see you edited your comment to be more informative rather than just dismissive ;)

@mightybyte Ok, so it's about breaking compilation, yet you say

>  I'm personally aware of io-streams being used in applications that serve millions of requests per day with strict latency SLAs.

This is has nothing to do with breaking compilation. It's just a total non-sequitor.

I appreciate the point about subtly 'breaking' performance with e.g. liftIO.  I also appreciate the trade-off not being worth it for your library. (And it's fair enough! I just don't think that "being used to serve X number of requests per second" is a reasonable argument against breaking compilation.)

**Comment by BardurArantsson** [comment]
More philosophically: I'm just a little sad the general ossification of the ecosystem. I suppose it might be an inevitability once there's enough money at stake, but that doesn't make it less sad. It sort of goes against the "avoid success at all cost" motto.

Just to be absolutely clear: I don't "blame" any particular person/library for any of this. It's just that there's this meta-process going on that's... not fun and will end badly, basically.

**Comment by mightybyte** [comment]
> This is has nothing to do with breaking compilation. It's just a total non-sequitor.

@BardurArantsson I wasn't talking about breaking compilation in that sentence.  It's not a non-sequitur.  It's directly applicable to the previous sentence talking about the performance impact.  I know that applications with those kinds of concerns are customers of this library and I'm not willing to impose a potential performance penalty on them.

> More philosophically: I'm just a little sad the general ossification of the ecosystem.

On the contrary, I don't want the core infrastructure I use to put me on a perpetual upgrade treadmill, forcing me to waste time making cosmetic updates to code that works just fine when I could be building new things.  We'll just have to agree to disagree.
